config/routes.rb
Rails.application.routes.draw do

  resources :rakuten_scrapings, only: [:new, :update, :destroy, :create] do
    member do
      get :edit
    end
  end
  
  get 'rakuten_scrapings/add_scraping', to:"rakuten_scrapings#add_scraping" 
  
  resources :lists, only: [:new, :create, :destroy, :show]

  get 'updates/new'
  get 'storages/new'
  
  #管理者画面
  resources :supervisors, only: [:show, :new, :create] do
    member do
      get :foods 
      get :recipes
      get :users
      get :rakuten_scrapings
    end
  end
  #管理者ログイン画面
  get 'supervisor_login', to: 'supervisor_sessions#new'
  post 'supervisor_login', to: 'supervisor_sessions#create'
  delete 'supervisor_logout', to: 'supervisor_sessions#destroy'

  resources :foods, only: [:update, :destroy] do
    member do
      get :edit
    end
  end

  root to:'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update] do
    member do
      get :like_recipes
      get :buy_storage_recipes
      get :edit
    end
  end  
  resources :recipes, only: [:new,:update] do
    member do
      get :edit
    end
  end
  get'recipes/category', to:"recipes#category" 
  get'recipes/random', to:"recipes#random"
  get'recipes/search', to:"recipes#search"
  
  resources :likes, only: [:create, :destroy]

  resources :storage_lists, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :rakuten_category_id, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
end

app/models/food.rb
class Food < ApplicationRecord
  
#食材登録
  has_many :storages, dependent: :destroy
  has_many :material_recipes, through: :storages, source: :recipe
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :list_name, presence: true
  has_many :list_recipes , dependent: :destroy
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :list
  belongs_to :recipe
end

app/models/rakuten_scraping.rb
class RakutenScraping < ApplicationRecord
  
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  serialize :materials
  validates :rakuten_recipe_id, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :food_image_url, presence: true, length: { maximum: 255 }
  validates :category_id, presence: true, length: { maximum: 255 }
  
  #お気に入り機能
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  
  #食材登録
  has_many :storages
  has_many :recipe_materials, through: :storages, source: :food
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_users, through: :storage_lists, source: :user
  
  
  
end

app/models/storage.rb
class Storage < ApplicationRecord
     belongs_to :recipe
     belongs_to :food
     belongs_to :rakuten_scraping
end

app/models/storage_list.rb
class StorageList < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  

end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
     before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
     has_secure_password

end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  mount_uploader :picture, PictureUploader
  
  #お気に入り機能
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  
  def fav(recipe)
    self.likes.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unfav(recipe)
    like = self.likes.find_by(recipe_id: recipe.id)
    like.destroy if like
  end

  def fav?(recipe)
    self.like_recipes.include?(recipe)
  end
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_recipes, through: :storage_lists, source: :recipe
  
  def record(recipe)
    self.storage_lists.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unrecord(recipe)
    storage_list = self.storage_lists.find_by(recipe_id: recipe.id)
    storage_list.destroy if storage_list
  end
  
  def record?(recipe)
    self.buy_storage_recipes.include?(recipe)
  end
  
end

app/controllers/supervisors_controller.rb
class SupervisorsController < ApplicationController
  before_action :require_supervisor_logged_in, only:[:show]
  before_action :correct_supervisor, only:[:show]
  
  def show
    @supervisor = Supervisor.find(params[:id])
  end

  def new
  end

  def create
  end
  
  def correct_supervisor
    supervisor = Supervisor.find(params[:id])
    unless supervisor.id == current_supervisor.id
      redirect_to root_url
      flash[:danger]="権限がありません"
    end
  end
  
  def foods
  end
  
  def recipes
  end
  
  def users
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
  
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include CategoriesHelper
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
=begin
  if @current_user
    return @current_user
  else
    @current_user = User.find_by(id: session[:user_id])
    return @current_user
  end
=end
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
=begin
    if current_user
      return true
    else
      return false
    end
=end
    !!current_user
  end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
     
end

app/views/supervisors/_tab.html.erb
<div class="col-xs-12">
  <ul class="nav nav-tabs nav-justified">
    <li class="<%= 'active' if current_page?(supervisor_path) %>"><%= link_to supervisor_path do %><%= current_supervisor.name %><% end %></li>
    <li class="<%= 'active' if current_page?(foods_supervisor_path) %>"><%= link_to foods_supervisor_path do %>foods<% end %></li>
    <li class="<%= 'active' if current_page?(recipes_supervisor_path) %>"><%= link_to recipes_supervisor_path do %>recipes<% end %></li>
    <li class="<%= 'active' if current_page?(users_supervisor_path) %>"><%= link_to users_supervisor_path do %>users<% end %></li>
    <li class="<%= 'active' if current_page?(rakuten_scrapings_supervisor_path) %>"><%= link_to rakuten_scrapings_supervisor_path do %>rakuten_scrapings<% end %></li>
  </ul>
</div>

app/views/supervisors/foods.html.erb
<div class="row">
  <h1><%= current_supervisor.name %>管理者ページ</h1>
  
  <%= render "supervisors/tab" %>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>no</th>
        <th>group</th>
        <th>name</th>
        <th>hiragana</th>
        <th>katakana</th>
        <th>kanzi</th>
        <th>other1</th>
        <th>other2</th>
        <th>other3</th>
      </tr>
    </thead>
    <tbody>
      <%= foods = Food.all.order('no ASC') %>
      <% foods.each do |f| %>
        <tr>
          <td><%= link_to f.id, edit_food_path(f) %></td>
          <td><%= f.no %></td>
          <% if f.no =="1"%>
            <td>肉</td>
          <% elsif f.no =="2"%>
            <td>魚</td>
          <% elsif f.no =="3"%>
            <td>野菜</td>
          <% elsif f.no =="4"%>
            <td>大豆加工食品</td>
          <% elsif f.no =="5"%>
            <td>お菓子関連</td>
          <% elsif f.no =="6"%>
            <td>その他</td>
          <% elsif f.no =="7"%>
            <td>薬味</td>
          <% elsif f.no =="8"%>
            <td>粉</td>
          <% elsif f.no =="9"%>
            <td>ソース</td>
          <% elsif f.no =="10"%>
            <td>調味料</td>
          <% else %>
            <td></td>
          <% end %>
          <td><%= f.name %></td>
          <td><%= f.hiragana %></td>
          <td><%= f.katakana %></td>
          <td><%= f.kanzi %></td>
          <td><%= f.other1 %></td>
          <td><%= f.other2 %></td>
          <td><%= f.other3 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  
</div>

app/views/supervisors/rakuten_scrapings.html.erb
<div class="row">
  <h1><%= current_supervisor.name %>管理者ページ</h1>
  
  <%= render "supervisors/tab" %>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>recipe_id</th>
        <th>rakuten_food_name</th>
        <th>rakuten_food_amount</th>
        <th>edit_food_name</th>
      </tr>
    </thead>
    <tbody>
      <%= scrapings = RakutenScraping.all.order('recipe_id ASC') %>
      <% scrapings.each do |f| %>
        <tr>
          <td><%= link_to f.id ,edit_rakuten_scraping_path(f), :target=>["_blank"]  %></td>
          <td><%= f.recipe_id %></td>
          <td><%= f.rakuten_food_name %></td>
          <td><%= f.rakuten_food_amount %></td>
          <td><%= f.edit_food_name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to "新規作成",rakuten_scrapings_add_scraping_path, :target=>["_blank"], class: "btn btn-success btn-s"  %>


</div>

app/views/supervisors/recipes.html.erb
<div class="row">
  <h1><%= current_supervisor.name %>管理者ページ</h1>
  
  <%= render "supervisors/tab" %>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>rakuten_recipe_id</th>
        <th>title</th>
        <th>materials</th>
        <th>update_date</th>
      </tr>
    </thead>
    <tbody>
      <%= recipes = Recipe.all.order('id ASC')%>
      <% recipes.each do |f| %>
        <tr>
          <td><%=link_to f.id, edit_recipe_path(f) %></td>
          <td><%= f.rakuten_recipe_id %></td>
          <td><%= f.title %></td>
          <td><%= f.materials %></td>
          <td><%= f.update_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  
</div>

app/views/supervisors/show.html.erb
<div class="row">
  <h1><%= current_supervisor.name %>管理者ページ</h1>
  
  <%= render "supervisors/tab" %>
  <%= render 'updates/update_button'%>
  <%= render 'rakuten_scrapings/scraping_button'%>
  <%= render 'storages/storage_button'%>

  
</div>

app/views/supervisors/users.html.erb
<div class="row">
  <h1><%= current_supervisor.name %>管理者ページ</h1>
  <%= render "supervisors/tab" %>

  <table class="table">
    <thead>
      <tr>
        <th>id</th>
        <th>name</th>
      </tr>
    </thead>
    <tbody>
      <%= users = User.all %>
      <% users.each do |f| %>
        <tr>
          <td><%= f.id %></td>
          <td><%= f.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  <%= storages = Storage.all %>
    <% storages.each do |s| %>
      <li><%= s.id %> ◇ <%= s.recipe_id %> ◇ <%= s.food_id %> </li>
    <% end %>
  
</div>