config/routes.rb
Rails.application.routes.draw do

  resources :rakuten_scrapings, only: [:new, :update, :destroy, :create] do
    member do
      get :edit
    end
  end
  
  get 'rakuten_scrapings/add_scraping', to:"rakuten_scrapings#add_scraping" 
  
  resources :lists, only: [:new, :create, :destroy, :show]

  get 'updates/new'
  get 'storages/new'
  
  #管理者画面
  resources :supervisors, only: [:show, :new, :create] do
    member do
      get :foods 
      get :recipes
      get :users
      get :rakuten_scrapings
    end
  end
  #管理者ログイン画面
  get 'supervisor_login', to: 'supervisor_sessions#new'
  post 'supervisor_login', to: 'supervisor_sessions#create'
  delete 'supervisor_logout', to: 'supervisor_sessions#destroy'

  resources :foods, only: [:update, :destroy] do
    member do
      get :edit
    end
  end

  root to:'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update] do
    member do
      get :like_recipes
      get :buy_storage_recipes
      get :edit
    end
  end  
  resources :recipes, only: [:new,:update] do
    member do
      get :edit
    end
  end
  get'recipes/category', to:"recipes#category" 
  get'recipes/random', to:"recipes#random"
  get'recipes/search', to:"recipes#search"
  
  resources :likes, only: [:create, :destroy]

  resources :storage_lists, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :rakuten_category_id, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
end

app/models/food.rb
class Food < ApplicationRecord
  
#食材登録
  has_many :storages, dependent: :destroy
  has_many :material_recipes, through: :storages, source: :recipe
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :list_name, presence: true
  has_many :list_recipes , dependent: :destroy
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :list
  belongs_to :recipe
end

app/models/rakuten_scraping.rb
class RakutenScraping < ApplicationRecord
  
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  serialize :materials
  validates :rakuten_recipe_id, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :food_image_url, presence: true, length: { maximum: 255 }
  validates :category_id, presence: true, length: { maximum: 255 }
  
  #お気に入り機能
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  
  #食材登録
  has_many :storages
  has_many :recipe_materials, through: :storages, source: :food
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_users, through: :storage_lists, source: :user
  
  
  
end

app/models/storage.rb
class Storage < ApplicationRecord
     belongs_to :recipe
     belongs_to :food
     belongs_to :rakuten_scraping
end

app/models/storage_list.rb
class StorageList < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  

end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
     before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
     has_secure_password

end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  mount_uploader :picture, PictureUploader
  
  #お気に入り機能
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  
  def fav(recipe)
    self.likes.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unfav(recipe)
    like = self.likes.find_by(recipe_id: recipe.id)
    like.destroy if like
  end

  def fav?(recipe)
    self.like_recipes.include?(recipe)
  end
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_recipes, through: :storage_lists, source: :recipe
  
  def record(recipe)
    self.storage_lists.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unrecord(recipe)
    storage_list = self.storage_lists.find_by(recipe_id: recipe.id)
    storage_list.destroy if storage_list
  end
  
  def record?(recipe)
    self.buy_storage_recipes.include?(recipe)
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
before_action :require_supervisor_logged_in, only: [:edit, :update]
  
  def category
    if params[:category_id].present?
      @category_recipes = Recipe.where(category_id: params[:category_id]) 
    else
      # パラメーターを受け取れていないなら
      @category_recipes = Recipe.where(category_id: Category.first.rakuten_category_id)
    end
  end
  
  def random
    # ちょとコメントすると、Rails.env.development? の場合は↑を、そうでない場合は下を
    # みたいな分岐条件で対処する、とかですかね...by @mentor-uchiyama
    # 但しこのような環境依存な分岐条件は、多用すると見通しが悪くなりがち。
    # 極力利用を控えることを検討されてみてください！
    if Rails.env.development?
      @random_recipes = Recipe.order("RAND()").limit(5)  #MySQL用
    else
      @random_recipes = Recipe.order("RANDOM()").limit(5)
    end
  end
  
  def search
    keyword = params[:keyword]
    @storages = []
    unless keyword == nil
      if Food.find_by(name: keyword)
        food_id = Food.find_by(name: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(hiragana: keyword)
        food_id = Food.find_by(hiragana: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(katakana: keyword)
        food_id = Food.find_by(katakana: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(kanzi: keyword)
        food_id = Food.find_by(kanzi: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(other1: keyword)
        food_id = Food.find_by(other1: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(other2: keyword)
        food_id = Food.find_by(other2: keyword).id
        @storages = Storage.where(food_id: food_id)
      elsif Food.find_by(other3: keyword)
        food_id = Food.find_by(other3: keyword).id
        @storages = Storage.where(food_id: food_id)
      else
        #対応するキーワードの食材が登録されていない場合
        @storages = []
      end
      @recipes = []
      @storages.each do |storage|
        @recipes << Recipe.find(storage.recipe_id)
      end
      @recipes.uniq!
    end
  end
  
  #データベースからカテゴリ別レシピランキングを表示
  def new
    update = Update.last.update_date
    @recipes= Recipe.where(update_date: update)
  end

  #レシピ編集用　
  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = 'recipe は正常に更新されました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'recipe は更新されませんでした'
      redirect_back(fallback_location: root_path)
    end
  end
  
  private
  #Strong Parameter
  def recipe_params
    params.require(:recipe).permit(:title, :materials)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include CategoriesHelper
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
=begin
  if @current_user
    return @current_user
  else
    @current_user = User.find_by(id: session[:user_id])
    return @current_user
  end
=end
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
=begin
    if current_user
      return true
    else
      return false
    end
=end
    !!current_user
  end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
     
end

app/views/recipes/_tab.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="<%= 'active' if current_page?(new_recipe_path) %>"><%= link_to new_recipe_path do %>カテゴリ別ランキング<% end %></li>
  <li class="<%= 'active' if current_page?(recipes_category_path) %>"><%= link_to recipes_category_path do %>カテゴリ別レシピ<% end %></li>
  <li class="<%= 'active' if current_page?(recipes_random_path) %>"><%= link_to recipes_random_path do %>ランダムレシピ<% end %></li>
  <li class="<%= 'active' if current_page?(recipes_search_path) %>"><%= link_to recipes_search_path do %>レシピ検索<% end %></li>

</ul>

app/views/recipes/category.html.erb
<%= render 'recipes/tab' %>
    <h1>カテゴリ別レシピ</h1>

<div class="container">
  <div class="row">
    <!--カテゴリ一覧　サイドバーに表示-->

    <div class="col-xs-2">
      <ul class="list-group">
        <% Category.all.each_with_index do |category,i| %>
        <% break if i==12 %>
          <li class="list-group-item">
            <%= link_to category.name,
            :action => "category", :category_id => category.rakuten_category_id %>
          </li>
        <% end %>
      </ul>
    </div>
   


<!--カテゴリ別レシピ表示部分-->
    <div class="col-xs-10">
      <% @category_recipes.each do |recipe| %>
        <div class="item">
          <div class="col-md-4 col-sm-5 col-xs-12">
            <div class="panel panel-default">
              <div class="panel-heading text-center">
                <a href= "<%= recipe.url %>" target="_blank">
                  <div class="sample2">
                    <img src="<%= recipe.food_image_url %>" alt="" >
                    <div class="mask">
		                  <div class="caption">楽天レシピで<br>詳細を確認する</div>
		                </div>
                  </div>
                </a>
              </div>
            <div class="panel-body">
            <!--表示が崩れるため文字は１５文字までとする-->
              <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
              <% if logged_in?%>
                <%= render 'likes/like_button', recipe: recipe %>
                <%= render 'storage_lists/storage_list_button', recipe: recipe %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>id: <%= @recipe.id %> のレシピ編集ページ</h1>

<%= @recipe.title %>
<%= @recipe.materials %>
<%= @recipe.materials[1] %>

<%= form_for(@recipe) do |f| %>
    <%= f.label :title,"レシピ名" %>
    <%= f.text_field :title, class: 'form-control' %>

    
   
  
    <%= f.submit "登録" %>

<% end %>

app/views/recipes/new.html.erb
  <div class="row">
    <%= render 'recipes/tab' %>
    
    <% categories = Category.all %>
    <% categories.each_with_index do |category,i| %>
      <%  break if i==12  %>
      <% recipes = Recipe.where(category_id: category.rakuten_category_id, update_date: Update.last.update_date) %>
      <div class="recipelist">
        <h2><%= category.name %></h2>
        <% recipes.each do |recipe|%>
          <!--表示部分 -->
          <div class="item">
            <div class="col-md-3 col-sm-4 col-xs-12">
              <div class="panel panel-default">
                <div class="panel-heading text-center">
                  <a href= "<%= recipe.url %>" target="_blank">
                    <div class="sample2">
                      <img src="<%= recipe.food_image_url %>" alt="" >
                      <div class="mask">
	                      <div class="caption">楽天レシピで<br>詳細を確認する</div>
		                  </div>
                    </div>
                  </a>
                </div>
                <div class="panel-body">
                  <!--表示が崩れるため文字は１５文字までとする-->
                  <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
                  <% if logged_in? %>
                    <%= render 'likes/like_button', recipe: recipe %>
                    <%= render 'storage_lists/storage_list_button', recipe: recipe %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    <% end %>
  </div>
  

app/views/recipes/random.html.erb
<%= render 'recipes/tab' %>
<h1>ランダムレシピ</h1>
<p>お忙しい方必見！</p>
<p>楽天レシピの中からランダムに５レシピを抽出します。</p>
<p>ついつい決まったものばかり食べてしまいがちですが、</p>
<p>この機会に新しいレシピに挑戦してみてください！</p>
<%= link_to '違うレシピを表示する', recipes_random_path, class: 'btn btn-success btn-lg' %>
<p></p>
<div class="item">
   <% @random_recipes.each do |recipe| %>
    <div class="col-md-3 col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <a href= "<%= recipe.url %>" target="_blank">
            <div class="sample2">
              <img src="<%= recipe.food_image_url %>" alt="" >
              <div class="mask">
		            <div class="caption">楽天レシピで<br>詳細を確認する</div>
		          </div>
            </div>
          </a>
        </div>
        <div class="panel-body">
          <!--表示が崩れるため文字は１５文字までとする-->
          <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
          <% if logged_in?%>
            <%= render 'likes/like_button', recipe: recipe %>
            <%= render 'storage_lists/storage_list_button', recipe: recipe %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/recipes/search.html.erb
<%= render 'recipes/tab' %>
<h1>レシピ検索</h1>
<p>食材の名前からレシピを検索！</p>
<p></p>

<div class="search">
  <div class="row">
    <div class="text-center">
      <%= form_tag(recipes_search_path, method: :get, class: 'form-inline') do %>
        <div class="form-group">
          <%= text_field_tag :keyword, @keyword, class: 'form-control input-lg', placeholder: "食材名を入力", size: 40 %>
        </div>
        <%= submit_tag '商品を検索', class: 'btn btn-success btn-lg' %>
      <% end %>
    </div>
  </div>
</div>

<div class="item">
  <% unless @recipes== nil %>
  <% @recipes.each do |recipe| %>
    <div class="col-md-3 col-sm-4 col-xs-12">
      <div class="panel panel-default">
        <div class="panel-heading text-center">
          <a href= "<%= recipe.url %>" target="_blank">
            <div class="sample2">
              <img src="<%= recipe.food_image_url %>" alt="" >
              <div class="mask">
		            <div class="caption">楽天レシピで<br>詳細を確認する</div>
		          </div>
            </div>
          </a>
        </div>
        <div class="panel-body">
          <!--表示が崩れるため文字は１５文字までとする-->
          <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
          <% if logged_in?%>
            <%= render 'likes/like_button', recipe: recipe %>
            <%= render 'storage_lists/storage_list_button', recipe: recipe %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>