config/routes.rb
Rails.application.routes.draw do

  resources :rakuten_scrapings, only: [:new, :update, :destroy, :create] do
    member do
      get :edit
    end
  end
  
  get 'rakuten_scrapings/add_scraping', to:"rakuten_scrapings#add_scraping" 
  
  resources :lists, only: [:new, :create, :destroy, :show]

  get 'updates/new'
  get 'storages/new'
  
  #管理者画面
  resources :supervisors, only: [:show, :new, :create] do
    member do
      get :foods 
      get :recipes
      get :users
      get :rakuten_scrapings
    end
  end
  #管理者ログイン画面
  get 'supervisor_login', to: 'supervisor_sessions#new'
  post 'supervisor_login', to: 'supervisor_sessions#create'
  delete 'supervisor_logout', to: 'supervisor_sessions#destroy'

  resources :foods, only: [:update, :destroy] do
    member do
      get :edit
    end
  end

  root to:'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update] do
    member do
      get :like_recipes
      get :buy_storage_recipes
      get :edit
    end
  end  
  resources :recipes, only: [:new,:update] do
    member do
      get :edit
    end
  end
  get'recipes/category', to:"recipes#category" 
  get'recipes/random', to:"recipes#random"
  get'recipes/search', to:"recipes#search"
  
  resources :likes, only: [:create, :destroy]

  resources :storage_lists, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :rakuten_category_id, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
end

app/models/food.rb
class Food < ApplicationRecord
  
#食材登録
  has_many :storages, dependent: :destroy
  has_many :material_recipes, through: :storages, source: :recipe
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :list_name, presence: true
  has_many :list_recipes , dependent: :destroy
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :list
  belongs_to :recipe
end

app/models/rakuten_scraping.rb
class RakutenScraping < ApplicationRecord
  
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  serialize :materials
  validates :rakuten_recipe_id, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :food_image_url, presence: true, length: { maximum: 255 }
  validates :category_id, presence: true, length: { maximum: 255 }
  
  #お気に入り機能
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  
  #食材登録
  has_many :storages
  has_many :recipe_materials, through: :storages, source: :food
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_users, through: :storage_lists, source: :user
  
  
  
end

app/models/storage.rb
class Storage < ApplicationRecord
     belongs_to :recipe
     belongs_to :food
     belongs_to :rakuten_scraping
end

app/models/storage_list.rb
class StorageList < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  

end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
     before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
     has_secure_password

end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  mount_uploader :picture, PictureUploader
  
  #お気に入り機能
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  
  def fav(recipe)
    self.likes.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unfav(recipe)
    like = self.likes.find_by(recipe_id: recipe.id)
    like.destroy if like
  end

  def fav?(recipe)
    self.like_recipes.include?(recipe)
  end
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_recipes, through: :storage_lists, source: :recipe
  
  def record(recipe)
    self.storage_lists.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unrecord(recipe)
    storage_list = self.storage_lists.find_by(recipe_id: recipe.id)
    storage_list.destroy if storage_list
  end
  
  def record?(recipe)
    self.buy_storage_recipes.include?(recipe)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :like_recipes, :buy_storage_recipes]
  before_action :correct_user, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @like_recipes = @user.like_recipes
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザーを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_edit_params)
      flash[:success] = 'recipe は正常に更新されました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'recipe は更新されませんでした'
      redirect_back(fallback_location: root_path)
    end
  end
  
  def like_recipes
    @user = User.find(params[:id])
    @likes = @user.like_recipes
    @likes.each do |like|
      @like_recipe = User.find(like.recipe_id)
    end
  end  
  
  def buy_storage_recipes
    make_list
    @user = User.find(params[:id])
    @buy_storage_recipes = @user.buy_storage_recipes
    #@buy_storage_recipes.each do |recipe|
      #@buy_storage_recipe = User.find(recipe.recipe_id)
  end

  def correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to root_url
      flash[:danger]="権限がありません"
    end
  end

  def make_list
    @list = []
    @user = User.find(params[:id])
    @user.buy_storage_recipes.each do|recipe|
      @storages = Storage.where(recipe_id: recipe.id)
      @storages.each do |s|
        @list << Food.find(s.food_id) 

      end 
    end
    @uniqlist = @list.uniq
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:picture)
  end
  
  def user_edit_params
    params.require(:user).permit(:picture)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include CategoriesHelper
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
=begin
  if @current_user
    return @current_user
  else
    @current_user = User.find_by(id: session[:user_id])
    return @current_user
  end
=end
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
=begin
    if current_user
      return true
    else
      return false
    end
=end
    !!current_user
  end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
     
end

app/views/users/buy_storage_recipes.html.erb
<!--買物リスト登録レシピ-->
  <h1>買物リスト</h1>
    <div class="item">
      <% current_user.buy_storage_recipes.each do |recipe| %>
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <a href= "<%= recipe.url %>" target="_blank">
                <div class="sample2">
                  <img src="<%= recipe.food_image_url %>" alt="" width="200" height="180" >
                  <div class="mask">
		                <div class="caption">楽天レシピで<br>詳細を確認する</div>
		              </div>
                </div>
              </a>
            </div>
            <div class="panel-body">
              <!--表示が崩れるため文字は１５文字までとする-->
              <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
              <%= render 'likes/like_button', recipe: recipe %>
              <%= render 'storage_lists/storage_list_button', recipe: recipe %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    
<!--買物リスト食材一覧-->
<div class="col-xs-12">
  <h1>食材リスト</h1>
  <table class="table">
    <thead>
      <tr>
        <th>食材</th>
        <% @user.buy_storage_recipes.each do |recipe|%>
          <th><%= truncate(recipe.title, length: 15) %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @uniqlist.each do |l| %>
            <tr>
              <td><%= l.name %></td>
              <% @user.buy_storage_recipes.each do |recipe|%>
                <% unless Storage.where(recipe_id: recipe.id, food_id: l.id).empty?%>
                  <% storages = Storage.where(recipe_id: recipe.id, food_id: l.id) %>
                  <% storage = storages.first %>
                  <td><%= RakutenScraping.find(storage.rakuten_scraping_id).rakuten_food_amount %></td>
                <% else %>
                  <td></td>
                <% end %>
              <% end %>
            </tr>
      <% end %>
    </tbody>
  </table>
</div>

<!--買物リスト登録フォーム-->
<div class="col-xs-12">
  <%= render 'lists/new_form' %>
</div>

app/views/users/edit.html.erb
  <h1>edit</h1>
  <%= form_for(@user) do |f| %>
    <div class="form-group">
      <%= f.label :picture, '画像' %>
      <%= f.file_field :picture %>
    </div>
    <div class="text-right">
      <%= f.submit '登録する', class: 'btn btn-success' %>
    </div>
  <% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :name, 'お名前' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :picture, '画像' %>
            <%= f.file_field :picture %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="name text-center">
    <h1><%= @user.name %></h1>

      <% if @user.picture.present? %>
        <div class="userimg">
          <img src="<%= @user.picture_url %>" alt="" >
        </div>
      <% else %>
        <div class="userimg">
          <img src="/images/logo_user.png" alt="" >
        </div>
      <% end %>
          
  </div>
  
<!--お気に入りレシピリスト-->
<div class="col-xs-12">
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo">お気に入りレシピリスト▼</button>
  <div id="demo" class="collapse">
    <div class="item">
      <% @like_recipes.each do |recipe| %>
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading text-center">
              <a href= "<%= recipe.url %>" target="_blank">
                <div class="sample2">
                  <img src="<%= recipe.food_image_url %>" alt="" width="200" height="180" >
                  <div class="mask">
		                <div class="caption">楽天レシピで<br>詳細を確認する</div>
		              </div>
                </div>
              </a>
            </div>
            <div class="panel-body">
              <!--表示が崩れるため文字は１５文字までとする-->
              <p class="item-title"><%= truncate(recipe.title, length: 15) %></p>
              <%= render 'likes/like_button', recipe: recipe %>
              <%= render 'storage_lists/storage_list_button', recipe: recipe %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="col-xs-12">
  <p>  </p>
</div>
<!--買い物リスト-->
<div class="col-xs-12">
  <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#demo2">【保存済】買い物リスト▼</button>
  <div id="demo2" class="collapse">
    <div class="item">
      <% lists = List.where(user_id: @user.id) %>
      <% lists.each do |list| %>
        <ul>
          <li><%= link_to list.list_name ,list_path(list) %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>
  