config/routes.rb
Rails.application.routes.draw do

  resources :rakuten_scrapings, only: [:new, :update, :destroy, :create] do
    member do
      get :edit
    end
  end
  
  get 'rakuten_scrapings/add_scraping', to:"rakuten_scrapings#add_scraping" 
  
  resources :lists, only: [:new, :create, :destroy, :show]

  get 'updates/new'
  get 'storages/new'
  
  #管理者画面
  resources :supervisors, only: [:show, :new, :create] do
    member do
      get :foods 
      get :recipes
      get :users
      get :rakuten_scrapings
    end
  end
  #管理者ログイン画面
  get 'supervisor_login', to: 'supervisor_sessions#new'
  post 'supervisor_login', to: 'supervisor_sessions#create'
  delete 'supervisor_logout', to: 'supervisor_sessions#destroy'

  resources :foods, only: [:update, :destroy] do
    member do
      get :edit
    end
  end

  root to:'toppages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :update] do
    member do
      get :like_recipes
      get :buy_storage_recipes
      get :edit
    end
  end  
  resources :recipes, only: [:new,:update] do
    member do
      get :edit
    end
  end
  get'recipes/category', to:"recipes#category" 
  get'recipes/random', to:"recipes#random"
  get'recipes/search', to:"recipes#search"
  
  resources :likes, only: [:create, :destroy]

  resources :storage_lists, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :rakuten_category_id, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
end

app/models/food.rb
class Food < ApplicationRecord
  
#食材登録
  has_many :storages, dependent: :destroy
  has_many :material_recipes, through: :storages, source: :recipe
  
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  validates :list_name, presence: true
  has_many :list_recipes , dependent: :destroy
end

app/models/list_recipe.rb
class ListRecipe < ApplicationRecord
  belongs_to :list
  belongs_to :recipe
end

app/models/rakuten_scraping.rb
class RakutenScraping < ApplicationRecord
  
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  serialize :materials
  validates :rakuten_recipe_id, presence: true, length: { maximum: 255 }
  validates :title, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :food_image_url, presence: true, length: { maximum: 255 }
  validates :category_id, presence: true, length: { maximum: 255 }
  
  #お気に入り機能
  has_many :likes
  has_many :like_users, through: :likes, source: :user
  
  #食材登録
  has_many :storages
  has_many :recipe_materials, through: :storages, source: :food
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_users, through: :storage_lists, source: :user
  
  
  
end

app/models/storage.rb
class Storage < ApplicationRecord
     belongs_to :recipe
     belongs_to :food
     belongs_to :rakuten_scraping
end

app/models/storage_list.rb
class StorageList < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  

end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
     before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
     has_secure_password

end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  
  mount_uploader :picture, PictureUploader
  
  #お気に入り機能
  has_many :likes
  has_many :like_recipes, through: :likes, source: :recipe
  
  def fav(recipe)
    self.likes.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unfav(recipe)
    like = self.likes.find_by(recipe_id: recipe.id)
    like.destroy if like
  end

  def fav?(recipe)
    self.like_recipes.include?(recipe)
  end
  
  #買物リスト機能storage
  has_many :storage_lists
  has_many :buy_storage_recipes, through: :storage_lists, source: :recipe
  
  def record(recipe)
    self.storage_lists.find_or_create_by(recipe_id: recipe.id)
  end
  
  def unrecord(recipe)
    storage_list = self.storage_lists.find_by(recipe_id: recipe.id)
    storage_list.destroy if storage_list
  end
  
  def record?(recipe)
    self.buy_storage_recipes.include?(recipe)
  end
  
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  include CategoriesHelper
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
=begin
  if @current_user
    return @current_user
  else
    @current_user = User.find_by(id: session[:user_id])
    return @current_user
  end
=end
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
=begin
    if current_user
      return true
    else
      return false
    end
=end
    !!current_user
  end
end

app/helpers/storages_helper.rb
module StoragesHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
     
end

app/views/toppages/index.html.erb
<% content_for :cover do %>
  <div class="cover">
    <div class="cover-inner">
      <div class="cover-contents">
        <h1>毎日のお買い物を週１回に。</h1>
      </div>
    </div>
  </div>
  <div class="top-button">
    <% if logged_in? %>
      <%= link_to 'マイページ', user_path(current_user), class: "square_btn" %>
    <% else %>
      <%= link_to '新規登録', signup_path ,class: "square_btn" %>
      <%= link_to 'ログイン', login_path, class: "square_btn" %>
    <% end %>
  </div>
<% end %>
<div class="top-img">
  <div class="col-md-4">
    <h3>買い物リスト機能</h3>
    <p>数日分の食材をまとめて買い出しに行けるよう、
    買い物リスト作成機能を搭載。
    マイページから過去に登録した「買い物リスト」
    を再確認することもできます。
    </p>
    <img src="/images/top1.png" >
  </div>

  <div class="col-md-4">
    <h3>豊富なレシピ</h3>
    <p>大手レシピサイト「楽天レシピ」から掲載しているため、
      おいしいレシピが盛りだくさんです。
      現在、厳選した<%= Recipe.last.id %>品のレシピを公開中！</p>
      
  </div>

  <div class="col-md-4">
    <h3>ランダムレシピ機能</h3>
    <p>毎日の献立を決めるのはとても大変・・・
      そんなお忙しい方はランダムレシピ機能をお試しください！
      楽天レシピの中からランダムで５つを紹介します。
      普段は作らないような新しいレシピとの出会いがあるかも・・・・</p>
  </div>
</div>

<div class ="toppage">
  <div class="col-md-12">
    <h3>買い物リストが簡単に作成可能。</h3>
    <p>買い物リストがあれば、お店でのお買い物もスムーズ。もちろん、買い物リストはスマホからも確認できます。</p>
    <p>また、家族へのおつかいもお願いしやすくなります。</p>

    <img src="/images/shopping_list.png" >
    <h2>もちろん使用は無料。早速使ってみましょう。</h2>
  </div>
</div>
<div class="col-md-12">
<div class="top-button">
    <% if logged_in? %>
      <%= link_to 'マイページ', user_path(current_user), class: "square_btn" %>
    <% else %>
      <%= link_to '新規登録', signup_path ,class: "square_btn" %>
      <%= link_to 'ログイン', login_path, class: "square_btn" %>
    <% end %>
</div>
</div>